/* eslint-disable */

/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.Contact', null, global);
goog.exportSymbol('proto.HowMe', null, global);
goog.exportSymbol('proto.HowMe.Region', null, global);
goog.exportSymbol('proto.ProfileMessage', null, global);
goog.exportSymbol('proto.ProfileMessage.ContactAddress', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ProfileMessage = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.ProfileMessage.repeatedFields_, null);
};
goog.inherits(proto.ProfileMessage, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.ProfileMessage.displayName = 'proto.ProfileMessage';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.ProfileMessage.repeatedFields_ = [4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ProfileMessage.prototype.toObject = function(opt_includeInstance) {
  return proto.ProfileMessage.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ProfileMessage} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ProfileMessage.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 7, ""),
    profileimage: jspb.Message.getFieldWithDefault(msg, 1, ""),
    userid: jspb.Message.getFieldWithDefault(msg, 2, ""),
    username: jspb.Message.getFieldWithDefault(msg, 3, ""),
    contactaddressList: jspb.Message.toObjectList(msg.getContactaddressList(),
    proto.ProfileMessage.ContactAddress.toObject, includeInstance),
    moodmessage: jspb.Message.getFieldWithDefault(msg, 5, ""),
    postnum: jspb.Message.getFieldWithDefault(msg, 6, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ProfileMessage}
 */
proto.ProfileMessage.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ProfileMessage;
  return proto.ProfileMessage.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ProfileMessage} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ProfileMessage}
 */
proto.ProfileMessage.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setProfileimage(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setUserid(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setUsername(value);
      break;
    case 4:
      var value = new proto.ProfileMessage.ContactAddress;
      reader.readMessage(value,proto.ProfileMessage.ContactAddress.deserializeBinaryFromReader);
      msg.addContactaddress(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setMoodmessage(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPostnum(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ProfileMessage.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ProfileMessage.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ProfileMessage} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ProfileMessage.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getProfileimage();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getUserid();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getUsername();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getContactaddressList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      proto.ProfileMessage.ContactAddress.serializeBinaryToWriter
    );
  }
  f = message.getMoodmessage();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getPostnum();
  if (f !== 0) {
    writer.writeInt32(
      6,
      f
    );
  }
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ProfileMessage.ContactAddress = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ProfileMessage.ContactAddress, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.ProfileMessage.ContactAddress.displayName = 'proto.ProfileMessage.ContactAddress';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ProfileMessage.ContactAddress.prototype.toObject = function(opt_includeInstance) {
  return proto.ProfileMessage.ContactAddress.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ProfileMessage.ContactAddress} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ProfileMessage.ContactAddress.toObject = function(includeInstance, msg) {
  var f, obj = {
    contact: jspb.Message.getFieldWithDefault(msg, 1, 0),
    address: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ProfileMessage.ContactAddress}
 */
proto.ProfileMessage.ContactAddress.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ProfileMessage.ContactAddress;
  return proto.ProfileMessage.ContactAddress.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ProfileMessage.ContactAddress} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ProfileMessage.ContactAddress}
 */
proto.ProfileMessage.ContactAddress.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.Contact} */ (reader.readEnum());
      msg.setContact(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setAddress(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ProfileMessage.ContactAddress.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ProfileMessage.ContactAddress.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ProfileMessage.ContactAddress} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ProfileMessage.ContactAddress.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getContact();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getAddress();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional Contact contact = 1;
 * @return {!proto.Contact}
 */
proto.ProfileMessage.ContactAddress.prototype.getContact = function() {
  return /** @type {!proto.Contact} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {!proto.Contact} value */
proto.ProfileMessage.ContactAddress.prototype.setContact = function(value) {
  jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional string address = 2;
 * @return {string}
 */
proto.ProfileMessage.ContactAddress.prototype.getAddress = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.ProfileMessage.ContactAddress.prototype.setAddress = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string id = 7;
 * @return {string}
 */
proto.ProfileMessage.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/** @param {string} value */
proto.ProfileMessage.prototype.setId = function(value) {
  jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional string profileImage = 1;
 * @return {string}
 */
proto.ProfileMessage.prototype.getProfileimage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.ProfileMessage.prototype.setProfileimage = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string userID = 2;
 * @return {string}
 */
proto.ProfileMessage.prototype.getUserid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.ProfileMessage.prototype.setUserid = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string userName = 3;
 * @return {string}
 */
proto.ProfileMessage.prototype.getUsername = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.ProfileMessage.prototype.setUsername = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * repeated ContactAddress contactAddress = 4;
 * @return {!Array.<!proto.ProfileMessage.ContactAddress>}
 */
proto.ProfileMessage.prototype.getContactaddressList = function() {
  return /** @type{!Array.<!proto.ProfileMessage.ContactAddress>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.ProfileMessage.ContactAddress, 4));
};


/** @param {!Array.<!proto.ProfileMessage.ContactAddress>} value */
proto.ProfileMessage.prototype.setContactaddressList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.ProfileMessage.ContactAddress=} opt_value
 * @param {number=} opt_index
 * @return {!proto.ProfileMessage.ContactAddress}
 */
proto.ProfileMessage.prototype.addContactaddress = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.ProfileMessage.ContactAddress, opt_index);
};


proto.ProfileMessage.prototype.clearContactaddressList = function() {
  this.setContactaddressList([]);
};


/**
 * optional string moodMessage = 5;
 * @return {string}
 */
proto.ProfileMessage.prototype.getMoodmessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.ProfileMessage.prototype.setMoodmessage = function(value) {
  jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional int32 postNum = 6;
 * @return {number}
 */
proto.ProfileMessage.prototype.getPostnum = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/** @param {number} value */
proto.ProfileMessage.prototype.setPostnum = function(value) {
  jspb.Message.setProto3IntField(this, 6, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.HowMe = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.HowMe, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.HowMe.displayName = 'proto.HowMe';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.HowMe.prototype.toObject = function(opt_includeInstance) {
  return proto.HowMe.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.HowMe} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.HowMe.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 6, ""),
    userid: jspb.Message.getFieldWithDefault(msg, 5, ""),
    region: jspb.Message.getFieldWithDefault(msg, 1, 0),
    isoccupation: jspb.Message.getFieldWithDefault(msg, 2, false),
    playtime: jspb.Message.getFieldWithDefault(msg, 3, ""),
    context: jspb.Message.getFieldWithDefault(msg, 4, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.HowMe}
 */
proto.HowMe.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.HowMe;
  return proto.HowMe.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.HowMe} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.HowMe}
 */
proto.HowMe.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setUserid(value);
      break;
    case 1:
      var value = /** @type {!proto.HowMe.Region} */ (reader.readEnum());
      msg.setRegion(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsoccupation(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setPlaytime(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setContext(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.HowMe.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.HowMe.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.HowMe} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.HowMe.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getUserid();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getRegion();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getIsoccupation();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getPlaytime();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getContext();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.HowMe.Region = {
  SEOUL: 0,
  DAEJEON: 1,
  DAEGU: 2,
  ULSAN: 3,
  GWANGJU: 4,
  BUSAN: 5,
  JEJU: 6,
  GYEONGGI: 7,
  GANGWON: 8,
  CHUNGBUK: 9,
  CHUNGNAM: 10,
  GYEONGBUK: 11,
  GYEONGNAM: 12,
  JEONBUK: 13,
  JEONNAM: 14
};

/**
 * optional string id = 6;
 * @return {string}
 */
proto.HowMe.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/** @param {string} value */
proto.HowMe.prototype.setId = function(value) {
  jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string userID = 5;
 * @return {string}
 */
proto.HowMe.prototype.getUserid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.HowMe.prototype.setUserid = function(value) {
  jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional Region region = 1;
 * @return {!proto.HowMe.Region}
 */
proto.HowMe.prototype.getRegion = function() {
  return /** @type {!proto.HowMe.Region} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {!proto.HowMe.Region} value */
proto.HowMe.prototype.setRegion = function(value) {
  jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional bool isOccupation = 2;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.HowMe.prototype.getIsoccupation = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 2, false));
};


/** @param {boolean} value */
proto.HowMe.prototype.setIsoccupation = function(value) {
  jspb.Message.setProto3BooleanField(this, 2, value);
};


/**
 * optional string playTime = 3;
 * @return {string}
 */
proto.HowMe.prototype.getPlaytime = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.HowMe.prototype.setPlaytime = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string context = 4;
 * @return {string}
 */
proto.HowMe.prototype.getContext = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.HowMe.prototype.setContext = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * @enum {number}
 */
proto.Contact = {
  KAKAOTALK: 0,
  FACEBOOK: 1,
  PHONE: 2,
  EMAIL: 3
};

goog.object.extend(exports, proto);
